name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting an issue to IOSF. Someone will address it soon.'' first issue'
        pr-message: 'Thank you for submitting a PR to IOSF. Someone will review it soon. Happy Coding :tada: '' first pr'
